version: '3.9'


services:

  # App backend service
  app-server:
    container_name: klv-project_app-server
    build:
      context: springboot-backend
      dockerfile: Dockerfile
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
    restart: no
    depends_on:
      app-db:
        condition: service_healthy
    environment:
      DB_SCHEMA: $DB_SCHEMA
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_SERVER: klv-project_app-db
      DB_PORT: $DB_DOCKER_PORT
    networks:
      - backend
      - frontend

  # App frontend service
  app-client:
    container_name: klv-project_app-client
    hostname: sun.klv.com # TODO: Change before deployment
    build:
      context: react-ui
      dockerfile: Dockerfile
      args:
        API_BASE_URL: 'http://localhost:${SPRING_DOCKER_PORT}/api'
    ports:
      - '${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}'
    restart: no
    depends_on:
      - app-server
    networks:
      - frontend

  # Database service (Mysql)
  app-db:
    container_name: klv-project_app-db
    build:
      context: mysql-database
      dockerfile: Dockerfile
    ports:
      - '${DB_LOCAL_PORT}:${DB_DOCKER_PORT}'
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_SCHEMA
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    networks:
      - backend


volumes:
  db-data:


networks:
  backend:
  frontend: