version: '3'
services:

  spring-back-end:
    image: "klv-project/springboot-backend:0.0.1"
    container_name: klv-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  react-front-end:
    image: "klv-project/react-ui:0.0.1"
    container_name: klv-ui
    ports:
      - "3001:3001"
    links:
      - spring-back-end