apiVersion: v1
kind: Secret
metadata:
  name: klv-db-secrets
  namespace: klv
type: Opaque
stringData:
  db-schema: "klv_database"
  db-user: "<your-username>"
  db-password: "<your-password>"
  db-root-password: "<your-root-password>"