apiVersion: v1
kind: Service
metadata:
  name: springboot-backend
  namespace: klv
spec:
  selector:
    app: springboot-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP